git submodule add git@github.com:rodydavis/fb_firestore.git packages/fb_firestore
git submodule add git@github.com:rodydavis/fb_storage.git packages/fb_storage
git submodule add git@github.com:rodydavis/fb_auth.git packages/fb_auth
git submodule add git@github.com:rodydavis/flutter_midi.git packages/flutter_midi
git submodule add git@github.com:rodydavis/mobile_popup.git packages/mobile_popup
git submodule add git@github.com:rodydavis/mobile_sidebar.git packages/mobile_sidebar
git submodule add git@github.com:rodydavis/sheet_music.git packages/sheet_music
git submodule add git@github.com:rodydavis/dynamic_tabs.git packages/dynamic_tabs
git submodule add git@github.com:rodydavis/data_tables.git packages/data_tables
git submodule add git@github.com:rodydavis/cupertino_controllers.git packages/cupertino_controllers
git submodule add git@github.com:rodydavis/dart_firebase.git packages/dart_firebase
git submodule add git@github.com:rodydavis/floating_search_bar.git packages/floating_search_bar
git submodule add git@github.com:rodydavis/easy_web_view.git packages/easy_web_view
git submodule add git@github.com:rodydavis/easy_google_maps.git packages/easy_google_maps
git submodule add git@github.com:fluttercommunity/persist_theme.git community/persist_theme
git submodule add git@github.com:fluttercommunity/flutter_whatsnew.git community/flutter_whatsnew
git submodule add git@github.com:fluttercommunity/app_review.git community/app_review
git submodule add git@github.com:fluttercommunity/get_version.git community/get_version
git submodule add git@github.com:fluttercommunity/flutter_sms.git community/flutter_sms
git submodule add git@github.com:fluttercommunity/native_widgets.git temp/native_widgets
git submodule add git@github.com:fluttercommunity/responsive_scaffold.git community/responsive_scaffold
git submodule add git@github.com:fluttercommunity/breakpoint.git community/breakpoint
